# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='client',
  serialized_pb='\n\x0c\x63ommon.proto\x12\x06\x63lient\"H\n\x05Heart\x12\x14\n\ttimestamp\x18\x01 \x01(\r:\x01\x30\x12\x13\n\x08utc_time\x18\x02 \x01(\r:\x01\x30\x12\x14\n\ttime_zone\x18\x03 \x01(\x05:\x01\x30')




_HEART = _descriptor.Descriptor(
  name='Heart',
  full_name='client.Heart',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='client.Heart.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='utc_time', full_name='client.Heart.utc_time', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_zone', full_name='client.Heart.time_zone', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=24,
  serialized_end=96,
)

DESCRIPTOR.message_types_by_name['Heart'] = _HEART

class Heart(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _HEART

  # @@protoc_insertion_point(class_scope:client.Heart)


# @@protoc_insertion_point(module_scope)
